// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by build_assets.py v2.3
// ============================================================================

#include "atlas_data.h"

// ---------------------------------------------------------------------------
// Sprite Metadata Array
// Format: { x, y, w, h, offX, offY, origW, origH }
// Note: x, y point to clean pixels (inside the extruded border)
// Note: w, h are the trimmed dimensions (visible pixels to render)
// ---------------------------------------------------------------------------

const SpriteMeta ASSET_SPRITES[SPRITE_COUNT] = {
    /* [  0] SPR_CACTUS                               */ {  761,    3,   16,   16,   0,   0,   16,   16 },
    /* [  1] SPR_CHARACTER_ZOMBIE_RUN0                */ {  368,    3,  149,  193,  23,  63,  192,  256 },
    /* [  2] SPR_CHARACTER_ZOMBIE_RUN1                */ {    3,    3,  167,  204,  12,  51,  192,  256 },
    /* [  3] SPR_CHARACTER_ZOMBIE_RUN2                */ {  174,    3,  190,  198,   1,  47,  192,  256 },
    /* [  4] SPR_ENEMY_IDLE                           */ {  736,    3,   21,   18,   2,   6,   24,   24 },
    /* [  5] SPR_FISH_BLUE                            */ {  649,    3,   58,   32,   3,  16,   64,   64 },
    /* [  6] SPR_MISSING                              */ {  781,    3,   16,   16,   0,   0,   16,   16 },
    /* [  7] SPR_PLAYER_IDLE0                         */ {  521,    3,  124,  123,   0,   0,  124,  123 },
    /* [  8] SPR_SOLDIER                              */ {  711,    3,   21,   32,   5,   0,   32,   32 }
};

// ---------------------------------------------------------------------------
// Animation Definitions Array
// Format: { startSpriteID, frameCount, defaultSpeed, loop }
// ---------------------------------------------------------------------------

const AnimDef ASSET_ANIMS[ANIM_COUNT] = {
    /* [ 0] ANIM_CHARACTER_ZOMBIE_RUN      */ {   1,  3, 0.10f, 1 }
};
