// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by build_assets.py v2.3
// ============================================================================

#ifndef ATLAS_DATA_H
#define ATLAS_DATA_H

#include <stdint.h>

// ---------------------------------------------------------------------------
// Sprite Metadata Structure
// ---------------------------------------------------------------------------

typedef struct {
    uint16_t x, y;         // Position in the atlas (clean pixels, inside extrusion)
    uint16_t w, h;         // Trimmed dimensions (visible pixels to render)
    uint16_t offX, offY;   // Offset from original top-left (after trimming)
    uint16_t origW, origH; // Original image dimensions before trimming
} SpriteMeta;

// ---------------------------------------------------------------------------
// Animation Definition Structure
// ---------------------------------------------------------------------------

typedef struct {
    uint16_t startSpriteID;  // ID of first frame sprite
    uint16_t frameCount;     // Number of frames in animation
    float defaultSpeed;      // Seconds per frame
    uint8_t loop;            // Whether animation loops (1=yes, 0=no)
} AnimDef;

// ---------------------------------------------------------------------------
// Sprite ID Enumeration
// ---------------------------------------------------------------------------

#define SPRITE_COUNT 9
#define ANIM_COUNT 1

typedef enum {
    SPR_CACTUS = 0,
    SPR_CHARACTER_ZOMBIE_RUN0 = 1,
    SPR_CHARACTER_ZOMBIE_RUN1 = 2,
    SPR_CHARACTER_ZOMBIE_RUN2 = 3,
    SPR_ENEMY_IDLE = 4,
    SPR_FISH_BLUE = 5,
    SPR_MISSING = 6,
    SPR_PLAYER_IDLE0 = 7,
    SPR_SOLDIER = 8
} SpriteID;

// ---------------------------------------------------------------------------
// Animation ID Enumeration
// ---------------------------------------------------------------------------

typedef enum {
    ANIM_CHARACTER_ZOMBIE_RUN = 0
} AnimID;

// ---------------------------------------------------------------------------
// External Data Arrays (defined in atlas_data.c)
// ---------------------------------------------------------------------------

extern const SpriteMeta ASSET_SPRITES[SPRITE_COUNT];
extern const AnimDef ASSET_ANIMS[ANIM_COUNT];

#endif // ATLAS_DATA_H
